apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      purpose: jenkins-shared-deployement
